version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_replica:
    image: postgres:15
    container_name: db_replica
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata_replica:/var/lib/postgresql/data

  backend1:
    build: ./practicadc-api
    container_name: backend1
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  backend2:
    build: ./practicadc-api
    container_name: backend2
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./practicadc
    container_name: frontend1
    depends_on:
      - backend1
      - backend2

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend1
      - backend2

volumes:
  pgdata:
  pgdata_replica:
